package com.jackhan.wgleadlife.bean;

import java.io.Serializable;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
public class Movie implements Serializable {

	/*
     * {"movie_id":"9742","movie_name":"绝地逃亡","movie_type":"3D/IMAX",
	 * "movie_release_date"
	 * :"2016-07-21","movie_nation":"中国,美国,中国香港","movie_starring":
	 * "成龙,范冰冰,约翰尼·纳什维尔,张蓝心,伊娃·托雷斯,保罗·菲利普·克拉克,马铁摩,吉丽,王敏德,Jai Day,皮埃尔·布迪厄,Charlie Rawes,乔尔·阿德里安,托默·奥兹,Sara Maria Forsberg,曾志伟,施诗,Johnson Phan,Svitlana Zavialova,Brayden Handcock,Youn Junghoon,赵文瑄,Daniel Garcia,安德鲁·达兹,廉政勋,郭品超"
	 * ,"movie_length":"111","movie_picture":
	 * "http://f.hiphotos.baidu.com/movie/pic/item/37d3d539b6003af38fd4761b3d2ac65c1038b65b.jpg"
	 * ,"movie_score":"8.7","movie_director":"雷尼·哈林","movie_tags":"喜剧,动作",
	 * "movie_message":"猫鼠游戏 异国逃亡","is_imax":1,"is_new":"1","movie_big_picture":
	 * "http://g.hiphotos.baidu.com/movie/pic/item/d439b6003af33a875f03aa61ce5c10385343b55b.jpg"
	 * ,"movies_wd":"绝地逃亡 热门电影"}
	 */
    /**
     * Not-null value.
     */
    private String movie_id;
    /**
     * Not-null value.
     */

    private String movie_name;

    private String movie_type;

    private java.util.Date movie_release_date;

    private String movie_nation;

    private String movie_starring;

    private String movie_length;

    private String movie_picture;

    private String movie_score;

    private String movie_director;

    private String movie_tags;

    private String movie_message;

    private String is_imax;

    private String is_new;

    private String movie_big_picture;

    private String movies_wd;

    public Movie() {
    }

    public Movie(String movie_id) {
        this.movie_id = movie_id;
    }

    public Movie(String movie_id, String movie_name, String movie_type,
                 java.util.Date movie_release_date, String movie_nation,
                 String movie_starring, String movie_length, String movie_picture,
                 String movie_score, String movie_director, String movie_tags,
                 String movie_message, String is_imax, String is_new,
                 String movie_big_picture, String movies_wd) {
        this.movie_id = movie_id;
        this.movie_name = movie_name;
        this.movie_type = movie_type;
        this.movie_release_date = movie_release_date;
        this.movie_nation = movie_nation;
        this.movie_starring = movie_starring;
        this.movie_length = movie_length;
        this.movie_picture = movie_picture;
        this.movie_score = movie_score;
        this.movie_director = movie_director;
        this.movie_tags = movie_tags;
        this.movie_message = movie_message;
        this.is_imax = is_imax;
        this.is_new = is_new;
        this.movie_big_picture = movie_big_picture;
        this.movies_wd = movies_wd;
    }

    /**
     * Not-null value.
     */
    public String getMovie_id() {
        return movie_id;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setMovie_id(String movie_id) {
        this.movie_id = movie_id;
    }

    /**
     * Not-null value.
     */
    public String getMovie_name() {
        return movie_name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the
     * database.
     */
    public void setMovie_name(String movie_name) {
        this.movie_name = movie_name;
    }

    public String getMovie_type() {
        return movie_type;
    }

    public void setMovie_type(String movie_type) {
        this.movie_type = movie_type;
    }

    public java.util.Date getMovie_release_date() {
        return movie_release_date;
    }

    public void setMovie_release_date(java.util.Date movie_release_date) {
        this.movie_release_date = movie_release_date;
    }

    public String getMovie_nation() {
        return movie_nation;
    }

    public void setMovie_nation(String movie_nation) {
        this.movie_nation = movie_nation;
    }

    public String getMovie_starring() {
        return movie_starring;
    }

    public void setMovie_starring(String movie_starring) {
        this.movie_starring = movie_starring;
    }

    public String getMovie_length() {
        return movie_length;
    }

    public void setMovie_length(String movie_length) {
        this.movie_length = movie_length;
    }

    public String getMovie_picture() {
        return movie_picture;
    }

    public void setMovie_picture(String movie_picture) {
        this.movie_picture = movie_picture;
    }

    public String getMovie_score() {
        return movie_score;
    }

    public void setMovie_score(String movie_score) {
        this.movie_score = movie_score;
    }

    public String getMovie_director() {
        return movie_director;
    }

    public void setMovie_director(String movie_director) {
        this.movie_director = movie_director;
    }

    public String getMovie_tags() {
        return movie_tags;
    }

    public void setMovie_tags(String movie_tags) {
        this.movie_tags = movie_tags;
    }

    public String getMovie_message() {
        return movie_message;
    }

    public void setMovie_message(String movie_message) {
        this.movie_message = movie_message;
    }

    public String getIs_imax() {
        return is_imax;
    }

    public void setIs_imax(String is_imax) {
        this.is_imax = is_imax;
    }

    public String getIs_new() {
        return is_new;
    }

    public void setIs_new(String is_new) {
        this.is_new = is_new;
    }

    public String getMovie_big_picture() {
        return movie_big_picture;
    }

    public void setMovie_big_picture(String movie_big_picture) {
        this.movie_big_picture = movie_big_picture;
    }

    public String getMovies_wd() {
        return movies_wd;
    }

    public void setMovies_wd(String movies_wd) {
        this.movies_wd = movies_wd;
    }

}
