package com.jackhan.wgleadlife.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.jackhan.wgleadlife.bean.WeatherResult;
import com.jackhan.wgleadlife.bean.Weather_Index;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEATHER__INDEX".
*/
public class Weather_IndexDao extends AbstractDao<Weather_Index, Long> {

    public static final String TABLENAME = "WEATHER__INDEX";

    /**
     * Properties of entity Weather_Index.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Zs = new Property(2, String.class, "zs", false, "ZS");
        public final static Property Tipt = new Property(3, String.class, "tipt", false, "TIPT");
        public final static Property Des = new Property(4, String.class, "des", false, "DES");
        public final static Property CurrentCity = new Property(5, String.class, "currentCity", false, "CURRENT_CITY");
    };

    private DaoSession daoSession;

    private Query<Weather_Index> weatherResult_IndexQuery;

    public Weather_IndexDao(DaoConfig config) {
        super(config);
    }
    
    public Weather_IndexDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEATHER__INDEX\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"ZS\" TEXT," + // 2: zs
                "\"TIPT\" TEXT," + // 3: tipt
                "\"DES\" TEXT," + // 4: des
                "\"CURRENT_CITY\" TEXT);"); // 5: currentCity
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEATHER__INDEX\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Weather_Index entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String zs = entity.getZs();
        if (zs != null) {
            stmt.bindString(3, zs);
        }
 
        String tipt = entity.getTipt();
        if (tipt != null) {
            stmt.bindString(4, tipt);
        }
 
        String des = entity.getDes();
        if (des != null) {
            stmt.bindString(5, des);
        }
 
        String currentCity = entity.getCurrentCity();
        if (currentCity != null) {
            stmt.bindString(6, currentCity);
        }
    }

    @Override
    protected void attachEntity(Weather_Index entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Weather_Index readEntity(Cursor cursor, int offset) {
        Weather_Index entity = new Weather_Index( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // zs
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // tipt
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // des
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // currentCity
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Weather_Index entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setZs(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTipt(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDes(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCurrentCity(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Weather_Index entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Weather_Index entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "index" to-many relationship of WeatherResult. */
    public List<Weather_Index> _queryWeatherResult_Index(String currentCity) {
        synchronized (this) {
            if (weatherResult_IndexQuery == null) {
                QueryBuilder<Weather_Index> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.CurrentCity.eq(null));
                weatherResult_IndexQuery = queryBuilder.build();
            }
        }
        Query<Weather_Index> query = weatherResult_IndexQuery.forCurrentThread();
        query.setParameter(0, currentCity);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWeatherResultDao().getAllColumns());
            builder.append(" FROM WEATHER__INDEX T");
            builder.append(" LEFT JOIN WEATHER_RESULT T0 ON T.\"CURRENT_CITY\"=T0.\"CURRENT_CITY\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Weather_Index loadCurrentDeep(Cursor cursor, boolean lock) {
        Weather_Index entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        WeatherResult weatherResult_fk = loadCurrentOther(daoSession.getWeatherResultDao(), cursor, offset);
        entity.setWeatherResult_fk(weatherResult_fk);

        return entity;    
    }

    public Weather_Index loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Weather_Index> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Weather_Index> list = new ArrayList<Weather_Index>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Weather_Index> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Weather_Index> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
